package com.louise.eveningloginexample



data class UserData(
    val id: String? = null, // User ID (optional, generated by Firebase)
    val username: String? = null, // Username
    val password: String? = null  // Password
)

